# Generated by Django 6.0.6 on 2026-07-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetcode',
            name='is_used',
        ),
    ]
