# Generated by Django 6.0.6 on 2026-07-26 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_passwordresetcode_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='occupation',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ENGINEER', 'Engineer'), ('SOFTWARE_DEVELOPER', 'Software Developer'), ('DESIGNER', 'Designer'), ('BUSINESS_OWNER', 'Business Owner'), ('OFFICE_WORKER', 'Office Worker'), ('FREELANCER', 'Freelancer'), ('HEALTHCARE_WORKER', 'Healthcare Worker'), ('GOVERNMENT_EMPLOYEE', 'Government Employee'), ('SALES_REPRESENTATIVE', 'Sales Representative'), ('CUSTOMER_SERVICE', 'Customer Service'), ('ACCOUNTANT', 'Accountant'), ('MARKETING_SPECIALIST', 'Marketing Specialist'), ('LAWYER', 'Lawyer'), ('ARCHITECT', 'Architect'), ('MECHANIC', 'Mechanic'), ('TECHNICIAN', 'Technician'), ('ELECTRICIAN', 'Electrician'), ('PLUMBER', 'Plumber'), ('CONSTRUCTION_WORKER', 'Construction Worker'), ('DRIVER', 'Driver'), ('CHEF', 'Chef'), ('CASHIER', 'Cashier'), ('RETAIL_WORKER', 'Retail Worker'), ('FACTORY_WORKER', 'Factory Worker'), ('FARMER', 'Farmer'), ('POLICE_OFFICER', 'Police Officer'), ('FIREFIGHTER', 'Firefighter'), ('MILITARY', 'Military'), ('SCIENTIST', 'Scientist'), ('RESEARCHER', 'Researcher'), ('JOURNALIST', 'Journalist'), ('WRITER', 'Writer'), ('CONTENT_CREATOR', 'Content Creator'), ('PHOTOGRAPHER', 'Photographer'), ('ARTIST', 'Artist'), ('MUSICIAN', 'Musician'), ('CONSULTANT', 'Consultant'), ('HUMAN_RESOURCES', 'Human Resources'), ('PROJECT_MANAGER', 'Project Manager'), ('ENTREPRENEUR', 'Entrepreneur'), ('SELF_EMPLOYED', 'Self-Employed'), ('UNEMPLOYED', 'Unemployed'), ('RETIRED', 'Retired'), ('OTHER', 'Other')], default='STUDENT', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('Asia/Manila', 'Asia/Manila (UTC+08:00)'), ('Asia/Tokyo', 'Asia/Tokyo (UTC+09:00)'), ('Asia/Seoul', 'Asia/Seoul (UTC+09:00)'), ('Asia/Shanghai', 'Asia/Shanghai (UTC+08:00)'), ('Asia/Singapore', 'Asia/Singapore (UTC+08:00)'), ('Asia/Bangkok', 'Asia/Bangkok (UTC+07:00)'), ('Asia/Jakarta', 'Asia/Jakarta (UTC+07:00)'), ('Asia/Dubai', 'Asia/Dubai (UTC+04:00)'), ('Europe/London', 'Europe/London'), ('Europe/Paris', 'Europe/Paris'), ('Europe/Berlin', 'Europe/Berlin'), ('America/New_York', 'America/New_York'), ('America/Chicago', 'America/Chicago'), ('America/Denver', 'America/Denver'), ('America/Los_Angeles', 'America/Los_Angeles'), ('Australia/Sydney', 'Australia/Sydney'), ('Pacific/Auckland', 'Pacific/Auckland')], default='Asia/Manila', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='bio',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
